#!/usr/bin/env python
"""Run the downstream validators and collect their headline numbers as
LaTeX macros in build/downstream.tex. Never hand-edit that file."""

import os
import re
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
REPORT = os.path.dirname(HERE)
REPO = os.path.abspath(os.path.join(REPORT, "..", "..", ".."))
PY = "/opt/homebrew/Caskroom/miniforge/base/envs/y3cl_je_macos/bin/python"

ENV = dict(os.environ,
           Y3_CLUSTER_CPP_DIR=REPO,
           PYTHONPATH=REPO + ":/Users/jesteves/cosmosis_y3/cosmosis")


def sci(x):
    """1.23e-04 -> $1.2\\times10^{-4}$"""
    m, e = f"{float(x):.1e}".split("e")
    return rf"${m}\times10^{{{int(e)}}}$"


def main():
    macros = {}

    # shear1h2h_max validator (adaptive reference + 2h->0 limit)
    out = subprocess.run(
        [PY, os.path.join(REPO, "src/pipelines/des_y3/shear_1h2h",
                          "python/0d/validate_shear1h2h_max.py"),
         os.path.join(REPO, "cosmosis-models/real_pipeline_extract_prj2h_output")],
        capture_output=True, text=True, env=ENV).stdout
    for key, pat in (("validatorGL", r"explicit-3d GL vs adaptive reference: ([\d.e+-]+)"),
                     ("validatorFast", r"fast path\s+vs adaptive reference: ([\d.e+-]+)"),
                     ("validatorLimit", r"2h->0 limit vs validated 1h fixed-GL: ([\d.e+-]+)")):
        m = re.search(pat, out)
        macros[key] = sci(m.group(1)) if m else r"\textbf{??}"
    macros["validatorStatus"] = "PASS" if "PASS" in out else r"\textbf{FAIL}"

    # halo_model test suite
    out = subprocess.run([PY, os.path.join(REPO, "test/halo_model.test.py")],
                         capture_output=True, text=True, env=ENV)
    txt = out.stdout + out.stderr
    m = re.search(r"Ran (\d+) tests", txt)
    macros["haloTestsRan"] = m.group(1) if m else "??"
    macros["haloTestsStatus"] = "OK" if re.search(r"^OK", txt, re.M) else r"\textbf{FAIL}"

    out_path = os.path.join(REPORT, "build", "downstream.tex")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("% generated by collect_downstream.py -- do not edit\n")
        for k, v in macros.items():
            f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
    print(f"wrote {out_path}: {macros}")


if __name__ == "__main__":
    main()
