#!/usr/bin/env python
"""External validation of the b_sel_marg wall (P1/I1/J) — issue #11.

Compares the production C++ wall (``BSelMargIntegrand.so`` outputs in
the fiducial dump) against a dump-fed ADAPTIVE quadrature reference
(``test/make_bsel_quad_truth_pins.py``): scipy adaptive-z quad
(epsrel 1e-8), per-z theta GL split at the exclusion/sigmoid features,
refined lt/lnM grids (3-5x production), all inputs from the same dump.
Reference self-convergence: 2x inner grids move it by <= 6e-6.

Measured production deviations (official nz=50 dump):

    2026-08-20 pre-fix:  P1 max 2.3e-3 / I1 max 1.7e-2 / J max 1.9e-2
                         (z-trending, worst at zob=0.575)
    after the #12 C++ fix (chi evaluated directly at the z nodes
    instead of double-resampled through zt_ref, commit series):
                         P1 max 2.7e-3 / I1 max 1.0e-2 (median 5.6e-3)
                         / J max 9.9e-3 -- the zob=0.575 kink excess is
                         GONE; deviations roughly halved.

Remaining causes, tracked in
docs/known_issues/distances_grid_resolution_defect.md:
  (a) the coarse 50-point distances table itself (chi slope error at
      the wing z nodes; removed by cp_camb nz=400 -- base ini/dump/pin
      regeneration pending a coordinated Perlmutter re-pin), and
  (b) fixed-grid truncation at the production knobs (residual max
      4.8e-3 on I1 with a dense distances grid).

Convention per the project's known-defect pins (sel_function,
radial_series, nfw_dsigma_mis): assertions stay at the DEFAULT 1e-3
tolerance, so the I1/J rows (and some P1 rows) are DELIBERATELY red
until the defect is fixed or explicitly accepted. Regenerate the pins
with make_bsel_quad_truth_pins.py after any fix.

Skips when the fiducial dump is absent.
"""
from __future__ import annotations

import sys
import unittest
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src" / "pipelines"))

DUMP_DIR = REPO / "docs" / "figs" / "real_pipeline_extract_prj2h_output"
HAS_DUMP = (DUMP_DIR / "b_sel_marg_p1").is_dir()
_SKIP_MSG = (f"requires a real-pipeline dump at {DUMP_DIR} -- run "
             "cosmosis docs/figs/real_pipeline_extract_prj2h.ini")

REL_TOL = 1.0e-3   # project default; I1/J deliberately red (see docstring)

# ---- pins generated by test/make_bsel_quad_truth_pins.py (2026-08-20) ----
# wall row order: (lambda_bin 0..3) x (zob 0.275, 0.425, 0.575)
QUAD_P1 = np.array([
    1.6425795800e+00, 2.0436347212e+00, 2.3995246367e+00, 3.5218422067e+00,
    2.0814798259e+00, 2.5631545564e+00, 2.9898955468e+00, 4.3538871532e+00,
    2.6105256562e+00, 3.1798231533e+00, 3.6861269290e+00, 5.3346600076e+00
])
QUAD_I1 = np.array([
    2.1311266221e-01, 2.6907128142e-01, 3.1654770082e-01, 4.4405934892e-01,
    2.1643714753e-01, 2.6801797509e-01, 3.1056131754e-01, 4.2401824443e-01,
    2.0942724063e-01, 2.5443067500e-01, 2.9077406053e-01, 3.8850490911e-01
])
QUAD_J = np.array([
    1.0425297731e-01, 1.3471937946e-01, 1.6164999439e-01, 2.3953666901e-01,
    1.0606831959e-01, 1.3464059949e-01, 1.5933313788e-01, 2.3020875667e-01,
    1.0283243432e-01, 1.2826174908e-01, 1.4987805350e-01, 2.1207099119e-01
])


@unittest.skipUnless(HAS_DUMP, _SKIP_MSG)
class TestBSelWallAgainstQuadTruth(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        from shared import datablock_models as dm
        src = dm.DumpSource(str(DUMP_DIR))
        cls.wall = dm.BSelWallVector.from_source(
            src, src.array("sel_function", "lambda_edges"))
        # pins assume the canonical wall ordering
        np.testing.assert_array_equal(cls.wall.lambda_bin,
                                      np.tile(np.arange(4), 3))
        np.testing.assert_allclose(
            cls.wall.zob, np.repeat([0.275, 0.425, 0.575], 4), rtol=1e-12)

    def _assert(self, got, pinned, label):
        dev = np.abs(got / pinned - 1.0)
        self.assertLessEqual(
            dev.max(), REL_TOL,
            f"{label}: max dev vs adaptive quad-truth {dev.max():.2e} "
            f"(rows {np.where(dev > REL_TOL)[0].tolist()}); known defect, "
            "see docs/known_issues/distances_grid_resolution_defect.md")

    def test_p1_matches_quad_truth(self):
        self._assert(self.wall.p1, QUAD_P1, "P1")

    def test_i1_matches_quad_truth(self):
        # DELIBERATELY red at 1e-3 (measured max 1.7e-2, z-trending).
        self._assert(self.wall.i1, QUAD_I1, "I1")

    def test_j_matches_quad_truth(self):
        # DELIBERATELY red at 1e-3 (measured max 1.9e-2, z-trending).
        self._assert(self.wall.j, QUAD_J, "J")

    def test_budget_identity_of_bsel_closure(self):
        # Downstream sanity that is INDEPENDENT of the defect above:
        # the bsel two-plateau closure must reproduce
        # b_sel -> B_small/B_large consistency: I1 + J = I2 > I1 > 0.
        self.assertTrue(np.all(self.wall.i1 > 0.0))
        self.assertTrue(np.all(self.wall.j > 0.0))
        self.assertTrue(np.all(self.wall.p1 > 0.0))


if __name__ == "__main__":
    unittest.main(verbosity=2)
