#!/usr/bin/env python
"""Generate the pinned external-reference arrays for pk_external.test.py
and xi_nl_external.test.py.

NOT a test. Run manually when the fiducial point or the reference
inputs change, then paste the printed literals into the two test files
(each pin block in the tests carries a "generated by" provenance line).

Inputs
------
validations/second_halo_term/outputs/pk_camb.npz
    Direct CAMB linear P(k,z) on the production (k_h, z) grid at the
    fiducial cosmology (mock_mcmc_widePlanck_values.ini), generated by
    validations/second_halo_term/01_make_pk_camb.py (CAMB, halofit
    Takahashi-2012 pinned for the p_k_nl array). Units: k in h/Mpc,
    P in (Mpc/h)^3, both comoving.

External xi reference
---------------------
mcfit.P2xi (FFTLog, lowring=True) applied to the SAME CAMB linear
P(k) -- an algorithm genuinely independent of the production transform
(cluster_toolkit xi_mm_at_r, fixed-cycle Hankel quadrature), following
the CLensPy pattern (P2xi + log-space resampling).

Usage
-----
    source ~/cosmosis_y3/cosmosis_init_macos.sh   # or any env with numpy+mcfit
    python -B test/make_external_reference_pins.py
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[1]
PK_NPZ = REPO / "validations" / "second_halo_term" / "outputs" / "pk_camb.npz"

# Pin sub-grid: spans the production grid without bloating the tests.
Z_IDX = [0, 3, 5, 8, 12, 24, 49]          # z in [0, 4]
K_IDX = [0, 80, 160, 240, 320, 400, 460, 505]   # k in [1e-4, 50] h/Mpc
XI_R = np.array([0.5, 1.0, 3.0, 10.0, 30.0, 50.0])  # cMpc/h, inside xi_nl grid


def fmt(a, per_line=4):
    a = np.asarray(a, dtype=float).ravel()
    chunks = [", ".join(f"{v:.10e}" for v in a[i:i + per_line])
              for i in range(0, a.size, per_line)]
    return ",\n    ".join(chunks)


def main():
    d = np.load(PK_NPZ)
    k_h, z, p_lin = d["k_h"], d["z"], d["p_k_lin"]

    z_pin = z[Z_IDX]
    k_pin = k_h[K_IDX]
    p_pin = p_lin[np.ix_(Z_IDX, K_IDX)]

    print("# ---- pk_external.test.py pins ----")
    print(f"Z_PIN = np.array([\n    {fmt(z_pin)}\n])")
    print(f"K_PIN = np.array([\n    {fmt(k_pin)}\n])")
    print(f"P_CAMB_PIN = np.array([\n    {fmt(p_pin)}\n]).reshape({len(Z_IDX)}, {len(K_IDX)})")
    print(f"# provenance: {PK_NPZ.relative_to(REPO)}; As={float(d['As']):.6e} "
          f"sigma8={float(d['sigma8']):.6f} h={float(d['h']):.4f} "
          f"omega_m={float(d['omega_m']):.6f}")
    print(f"# measured emulator-vs-CAMB (full grid): max={float(d['dump_dev_max']):.3e} "
          f"median={float(d['dump_dev_median']):.3e}")

    # ---- xi pins: FFTLog transform of the same CAMB linear P(k) ----
    from mcfit import P2xi
    xi_pin = np.empty((len(Z_IDX), XI_R.size))
    for row, iz in enumerate(Z_IDX):
        r_fft, xi_fft = P2xi(k_h, lowring=True)(p_lin[iz], extrap=True)
        sel = (r_fft > 0.05) & (r_fft < 300.0)
        xi_pin[row] = np.exp(np.interp(np.log(XI_R), np.log(r_fft[sel]),
                                       np.log(np.abs(xi_fft[sel]))))
        xi_pin[row] *= np.sign(np.interp(np.log(XI_R), np.log(r_fft[sel]),
                                         xi_fft[sel]))

    print("\n# ---- xi_nl_external.test.py pins ----")
    print(f"Z_PIN = np.array([\n    {fmt(z_pin)}\n])")
    print(f"R_PIN = np.array([\n    {fmt(XI_R)}\n])  # cMpc/h")
    print(f"XI_FFTLOG_PIN = np.array([\n    {fmt(xi_pin)}\n]).reshape({len(Z_IDX)}, {XI_R.size})")
    print("# provenance: mcfit.P2xi(lowring=True, extrap=True) on pk_camb.npz p_k_lin,")
    print("#             log-log resampled onto R_PIN (CLensPy FFTLog pattern)")

    # ---- measure current dump agreement so the test gates are informed ----
    dump = REPO / "docs" / "figs" / "real_pipeline_extract_prj2h_output"
    if dump.is_dir():
        kd = np.loadtxt(dump / "matter_power_lin" / "k_h.txt")
        zd = np.loadtxt(dump / "matter_power_lin" / "z.txt")
        pd_ = np.loadtxt(dump / "matter_power_lin" / "p_k.txt").reshape(zd.size, kd.size)
        dev = np.abs(pd_[np.ix_(Z_IDX, K_IDX)] / p_pin - 1.0)
        print(f"\n# measured dump-vs-CAMB at the P pins: max={dev.max():.3e} "
              f"median={np.median(dev):.3e}")

        rx = np.loadtxt(dump / "xi_nl" / "r.txt")
        zx = np.loadtxt(dump / "xi_nl" / "z.txt")
        xx = np.loadtxt(dump / "xi_nl" / "xi_nl.txt").reshape(zx.size, rx.size)
        from scipy.interpolate import RegularGridInterpolator
        itp = RegularGridInterpolator((zx, np.log(rx)), xx)
        pts = np.stack(np.meshgrid(z_pin, np.log(XI_R), indexing="ij"), axis=-1)
        xd = itp(pts)
        dev = np.abs(xd / xi_pin - 1.0)
        print(f"# measured dump xi_nl vs FFTLog at the xi pins: max={dev.max():.3e} "
              f"median={np.median(dev):.3e}")
        print("# per-z max:", np.array2string(dev.max(axis=1), precision=2))


if __name__ == "__main__":
    main()
