#!/usr/bin/env python
"""External validation of the pipeline's linear P(k) input (issue #11 suite).

Compares the production ``matter_power_lin`` table (published by
``cp_camb.py``, the CosmoPower linear-P(k) emulator) against DIRECT CAMB
values at the same fiducial point -- an external reference, not a port
of the production code. The pinned values were generated by
``test/make_external_reference_pins.py`` from
``validations/second_halo_term/outputs/pk_camb.npz`` (itself produced by
``validations/second_halo_term/01_make_pk_camb.py``: CAMB at the
``mock_mcmc_widePlanck_values.ini`` fiducial on the production (k, z)
grid; k in h/Mpc, P in (Mpc/h)^3, comoving).

Tolerances are the emulator's measured intrinsic accuracy, NOT the
project 1e-3 default: emulator-vs-CAMB over the full 50x506 grid is
max 3.56e-3 / median 7.8e-4 (see pk_camb.npz dump_dev_*), and at the
pins below max 3.56e-3 / median 5.7e-4. Gates: max 5e-3, median 1.5e-3.
A failure here means the emulator (or its wiring) drifted from CAMB --
e.g. wrong weights file, wrong parameter mapping, or a unit change.

Skips (like the other dump-fed suites) when the fiducial dump is absent:
regenerate with  cosmosis cosmosis-models/real_pipeline_extract_prj2h.ini
(cp_camb paths point at pscratch; override them locally, see
BUILDING/building_macos docs).

Linear P(k) only, deliberately: the nonlinear input does not exist yet
(issue #9, accepted for now). pk_camb.npz already carries the Takahashi
halofit ``p_k_nl`` reference for the future nonlinear acceptance gate.
"""
from __future__ import annotations

import unittest
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[1]
DUMP_DIR = REPO / "cosmosis-models" / "real_pipeline_extract_prj2h_output"
HAS_DUMP = (DUMP_DIR / "matter_power_lin").is_dir()
_SKIP_MSG = (f"requires a real-pipeline dump at {DUMP_DIR} -- run "
             "cosmosis cosmosis-models/real_pipeline_extract_prj2h.ini")

# ---- pins generated by test/make_external_reference_pins.py (2026-08-20) ----
# provenance: validations/second_halo_term/outputs/pk_camb.npz;
# As=2.100960e-09 sigma8=0.823800 h=0.6766 omega_m=0.311049
Z_PIN = np.array([
    0.0000000000e+00, 2.4489795918e-01, 4.0816326531e-01, 6.5306122449e-01,
    9.7959183673e-01, 1.9591836735e+00, 4.0000000000e+00
])
K_PIN = np.array([
    1.0000000000e-04, 7.9947912670e-04, 6.3916687403e-03, 5.1100057427e-02,
    4.0853429286e-01, 3.2661463968e+00, 1.5528910755e+01, 5.0000000000e+01
])
P_CAMB_PIN = np.array([
    4.2583090178e+02, 3.1328801124e+03, 1.7757830426e+04, 1.2390569640e+04,
    4.9420309161e+02, 4.0395263310e+00, 7.2410519678e-02, 3.1322819248e-03,
    3.2873578515e+02, 2.4189875388e+03, 1.3712259481e+04, 9.5677747058e+03,
    3.8161477472e+02, 3.1192494892e+00, 5.5914087468e-02, 2.4186882014e-03,
    2.7719354449e+02, 2.0399862738e+03, 1.1564502340e+04, 8.0691785098e+03,
    3.2184268691e+02, 2.6306833103e+00, 4.7156284229e-02, 2.0398452790e-03,
    2.1678531724e+02, 1.5957433316e+03, 9.0470358650e+03, 6.3126192141e+03,
    2.5178154929e+02, 2.0580159902e+00, 3.6890928845e-02, 1.5957857656e-03,
    1.6012576226e+02, 1.1789994776e+03, 6.6854017680e+03, 4.6647910455e+03,
    1.8605720384e+02, 1.5207976356e+00, 2.7260985407e-02, 1.1792092341e-03,
    7.6307256029e+01, 5.6227761750e+02, 3.1904012760e+03, 2.2261586133e+03,
    8.8791334306e+01, 7.2576380673e-01, 1.3009554484e-02, 5.6270495154e-04,
    2.7305561302e+01, 2.0145343900e+02, 1.1451556400e+03, 7.9909188051e+02,
    3.1872157347e+01, 2.6051683015e-01, 4.6697386175e-03, 2.0193471970e-04
]).reshape(7, 8)

MAX_TOL = 5.0e-3     # emulator intrinsic, measured max 3.56e-3
MEDIAN_TOL = 1.5e-3  # measured median 5.7e-4 at the pins


@unittest.skipUnless(HAS_DUMP, _SKIP_MSG)
class TestLinearPkAgainstCamb(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        sec = DUMP_DIR / "matter_power_lin"
        cls.k = np.loadtxt(sec / "k_h.txt")
        cls.z = np.loadtxt(sec / "z.txt")
        cls.p = np.loadtxt(sec / "p_k.txt").reshape(cls.z.size, cls.k.size)

    def _pin_indices(self, grid, pins):
        idx = np.searchsorted(grid, pins)
        idx = np.clip(idx, 0, grid.size - 1)
        # accept the left neighbour when it is the closer grid point
        left = np.clip(idx - 1, 0, grid.size - 1)
        idx = np.where(np.abs(grid[left] - pins) < np.abs(grid[idx] - pins),
                       left, idx)
        np.testing.assert_allclose(grid[idx], pins, rtol=1e-9,
                                   err_msg="production grid moved; regenerate "
                                   "pins with make_external_reference_pins.py")
        return idx

    def test_fiducial_point_matches_reference_cosmology(self):
        vals = np.loadtxt(DUMP_DIR / "cosmological_parameters" / "values.txt",
                          dtype=str, delimiter="=", usecols=(0, 1))
        d = {k.strip(): v.strip() for k, v in vals}
        self.assertAlmostEqual(float(d["h0"]), 0.6766, places=4)
        self.assertAlmostEqual(float(d["omega_m"]), 0.311049, places=5)
        self.assertAlmostEqual(float(d["sigma8"]), 0.8238, places=4)

    def test_linear_pk_matches_direct_camb(self):
        zi = self._pin_indices(self.z, Z_PIN)
        ki = self._pin_indices(self.k, K_PIN)
        dev = np.abs(self.p[np.ix_(zi, ki)] / P_CAMB_PIN - 1.0)
        self.assertLessEqual(dev.max(), MAX_TOL,
                             f"max emulator-vs-CAMB dev {dev.max():.2e}")
        self.assertLessEqual(np.median(dev), MEDIAN_TOL,
                             f"median emulator-vs-CAMB dev {np.median(dev):.2e}")

    def test_growth_is_scale_independent_and_monotonic(self):
        # Linear P(k,z)/P(k,0) must be a scale-independent, decreasing D^2(z).
        zi = self._pin_indices(self.z, Z_PIN)
        ki = self._pin_indices(self.k, K_PIN)
        ratio = self.p[np.ix_(zi, ki)] / self.p[np.ix_([0], ki)]
        d2 = ratio.mean(axis=1)
        np.testing.assert_allclose(
            ratio, np.broadcast_to(d2[:, None], ratio.shape), rtol=2e-2)
        self.assertTrue(np.all(np.diff(d2) < 0.0))


if __name__ == "__main__":
    unittest.main(verbosity=2)
