#!/usr/bin/env python
"""External validation of the projection lensing DSigma_prj — issue #11.

Compares the production ``dsigma_prj`` (DSigmaPrjEvaluator.so /
sp_detail::ShearPrjCore) rnd/cl channels in the fiducial dump against a
dump-fed ADAPTIVE reference (``test/make_shear_prj_quad_truth_pins.py``):
scipy adaptive-z quad_vec with ring breakpoints, 3x-refined
feature-aligned log-GL theta panels, 3x-refined lnM GL — an independent
quadrature of the same integrand definition, NOT a port of the
production ring+wings fixed grid (the existing cross-backend tests
already cover port identity at 1e-8).

Measured production deviations (2026-08-20, official nz=50 dump), pinned
subset (lambda_bin 0 @ zob=0.275 and 3 @ zob=0.575; R = 0.26 / 1.62 /
10.01 cMpc/h):

    rnd: +2.6e-2 .. +3.0e-2 at R=0.26   <- innermost-radius excess,
         +5.4e-3 .. +9.1e-3 at R >= 1.6    the known wall-edge
                                           convergence question
    cl:  +2.2e-2 .. +2.3e-2 at R=0.26,  <= 1.5e-3 at R >= 1.6
    vals (rnd+cl): +2.3e-2 .. +2.5e-2 inner, <= 5.9e-3 outer

This quantifies, against an independent adaptive reference, the
previously acknowledged full_ltmz-CUDA finding ("median 9.5e-4, max
2.2% at innermost radii" — shear_prj_cross_backend.test.py docstring)
and adds the distances-grid contribution at larger R
(docs/known_issues/distances_grid_resolution_defect.md).

Convention: assertions at the DEFAULT 1e-3 tolerance — the inner-radius
rows are DELIBERATELY red until the wall-edge convergence question is
resolved or the deviation is explicitly accepted. Regenerate pins with
make_shear_prj_quad_truth_pins.py after any fix.

Skips when the fiducial dump is absent.
"""
from __future__ import annotations

import re
import unittest
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[1]
DUMP_DIR = REPO / "docs" / "figs" / "real_pipeline_extract_prj2h_output"
HAS_DUMP = (DUMP_DIR / "dsigma_prj").is_dir()
_SKIP_MSG = (f"requires a real-pipeline dump at {DUMP_DIR} -- run "
             "cosmosis docs/figs/real_pipeline_extract_prj2h.ini")

REL_TOL = 1.0e-3   # project default; inner-R rows deliberately red

# ---- pins generated by test/make_shear_prj_quad_truth_pins.py ----
# (2026-08-20; reference 2x-grid self-convergence quoted in that script)
QUAD_PINS = [  # (lambda_bin, zob, R_cMpch, rnd, cl)
    # regenerated 2026-08-20 after the #12 chi-direct fix (the wall ->
    # bsel plateaus feed the cl channel, so the truth moved with them)
    (0, 0.275, 0.26070, 2.8459626572e-01, 9.3796754953e-01),
    (0, 0.275, 1.61810, 1.5235966124e+00, 2.7164997709e+00),
    (0, 0.275, 10.01070, 3.9564548652e+00, 1.5402625037e+00),
    (3, 0.575, 0.26070, 4.4395886776e-01, 1.8194948623e+00),
    (3, 0.575, 1.61810, 2.3033337835e+00, 6.9520332042e+00),
    (3, 0.575, 10.01070, 5.8616660594e+00, 4.3254589439e+00),
]


def _wall_from_ini():
    """dsigma_prj publishes only vals/rnd/cl; wall geometry lives in the
    extract ini (the #10-class metadata gap for this section)."""
    text = (REPO / "docs" / "figs"
            / "real_pipeline_extract_prj2h.ini").read_text()
    sec = re.search(r"^\[dsigma_prj\]\s*$(.*?)(?:^\[|\Z)", text,
                    re.S | re.M).group(1)

    def vec(key):
        m = re.search(rf"^{key}\s*=\s*(.+)$", sec, re.M)
        return np.array([float(v) for v in m.group(1).split()])

    return (vec("lambda_bin").astype(int), 0.5 * (vec("zo_low")
            + vec("zo_high")), vec("radii"))


@unittest.skipUnless(HAS_DUMP, _SKIP_MSG)
class TestDSigmaPrjAgainstQuadTruth(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.lb, cls.zob, cls.radii = _wall_from_ini()
        cls.rnd = np.loadtxt(DUMP_DIR / "dsigma_prj" / "rnd.txt")
        cls.cl = np.loadtxt(DUMP_DIR / "dsigma_prj" / "cl.txt")
        assert cls.rnd.size == cls.lb.size

    def _row(self, lb, zob, r):
        m = ((self.lb == lb) & np.isclose(self.zob, zob)
             & np.isclose(self.radii, r))
        (idx,) = np.nonzero(m)
        self.assertEqual(idx.size, 1, f"wall row ({lb},{zob},{r}) not found")
        return int(idx[0])

    def _channel_devs(self, channel, col):
        devs = {}
        for lb, zob, r, rnd_pin, cl_pin in QUAD_PINS:
            i = self._row(lb, zob, r)
            pin = (rnd_pin, cl_pin)[col]
            devs[(lb, zob, r)] = abs(channel[i] / pin - 1.0)
        return devs

    def test_rnd_channel_matches_quad_truth(self):
        # DELIBERATELY red at 1e-3 (measured +0.5%..+3.0%, worst at
        # the innermost radius) -- see module docstring.
        devs = self._channel_devs(self.rnd, 0)
        worst = max(devs.values())
        self.assertLessEqual(
            worst, REL_TOL,
            f"rnd max dev vs adaptive quad-truth {worst:.2e} at "
            f"{max(devs, key=devs.get)}; known inner-radius convergence "
            "defect, see module docstring")

    def test_cl_channel_matches_quad_truth(self):
        # DELIBERATELY red at 1e-3 for the innermost radius
        # (measured +2.2e-2 there; <= 1.5e-3 at R >= 1.6).
        devs = self._channel_devs(self.cl, 1)
        worst = max(devs.values())
        self.assertLessEqual(
            worst, REL_TOL,
            f"cl max dev vs adaptive quad-truth {worst:.2e} at "
            f"{max(devs, key=devs.get)}; known inner-radius convergence "
            "defect, see module docstring")

    def test_cl_channel_outer_radii_within_default_tolerance(self):
        # The 2h-regime radii (the Buzzard large-scale window) must NOT
        # regress: cl at R >= 1.6 cMpc/h currently agrees with the
        # adaptive reference to <= 1.5e-3. Gate at 2e-3.
        devs = self._channel_devs(self.cl, 1)
        outer = {k: v for k, v in devs.items() if k[2] > 1.0}
        self.assertLessEqual(max(outer.values()), 2.0e-3,
                             f"outer-radius cl regressed: {outer}")


if __name__ == "__main__":
    unittest.main(verbosity=2)
