#!/usr/bin/env python
"""External validation of the production xi_NL table (issue #11 suite).

Compares the ``xi_nl`` datablock table (published by
``halo_model_cosmosis.py`` via cluster_toolkit ``xi_mm_at_r``, a
fixed-cycle Hankel quadrature) against an INDEPENDENT transform of the
same fiducial linear P(k): mcfit ``P2xi`` (FFTLog, lowring, the CLensPy
pattern). Different algorithm, different code -- a genuine method-level
cross-check, unlike the port-identity tests.

Pins generated by ``test/make_external_reference_pins.py`` from
``validations/second_halo_term/outputs/pk_camb.npz`` (direct CAMB linear
P(k) at the mock_mcmc_widePlanck fiducial). r in cMpc/h.

Tolerances are the measured CROSS-METHOD envelope, not the project 1e-3
default. Three effects stack: (a) emulator-vs-CAMB P(k) input (max
0.36%), (b) Hankel-vs-FFTLog transform, (c) log-log interpolation on
the 128-point production r-grid. Measured on 2026-08-20:
max 1.47e-2 (at r=50), median 4.3e-3, r-structured and z-independent --
the signature of (b)+(c), consistent with the 4-way transform bench in
validations/second_halo_term (cluster_toolkit / CLensPy / pyccl / CLMM
agree to <=1.6%). Gates: max 2e-2, median 8e-3.

NOTE (issue #9): this table currently carries LINEAR xi in every run --
accepted for now. This test validates the transform, not the
linear-vs-nonlinear physics choice; when the nonlinear input lands, the
pins must be regenerated from ``p_k_nl`` (Takahashi, already in
pk_camb.npz).

Skips when the fiducial dump is absent (regenerate with
cosmosis cosmosis-models/real_pipeline_extract_prj2h.ini).
"""
from __future__ import annotations

import unittest
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[1]
DUMP_DIR = REPO / "cosmosis-models" / "real_pipeline_extract_prj2h_output"
HAS_DUMP = (DUMP_DIR / "xi_nl").is_dir()
_SKIP_MSG = (f"requires a real-pipeline dump at {DUMP_DIR} -- run "
             "cosmosis cosmosis-models/real_pipeline_extract_prj2h.ini")

# ---- pins generated by test/make_external_reference_pins.py (2026-08-20) ----
Z_PIN = np.array([
    0.0000000000e+00, 2.4489795918e-01, 4.0816326531e-01, 6.5306122449e-01,
    9.7959183673e-01, 1.9591836735e+00, 4.0000000000e+00
])
R_PIN = np.array([
    5.0000000000e-01, 1.0000000000e+00, 3.0000000000e+00, 1.0000000000e+01,
    3.0000000000e+01, 5.0000000000e+01
])  # cMpc/h
XI_FFTLOG_PIN = np.array([
    9.6215222813e+00, 5.5829062871e+00, 1.8922981088e+00, 3.5788761809e-01,
    3.6385412242e-02, 8.0238131077e-03, 7.4295661773e+00, 4.3110194561e+00,
    1.4611984494e+00, 2.7635435909e-01, 2.8096155551e-02, 6.1958397009e-03,
    6.2658773092e+00, 3.6357869123e+00, 1.2323317459e+00, 2.3306912369e-01,
    2.3695467932e-02, 5.2253896740e-03, 4.9018739283e+00, 2.8443214901e+00,
    9.6406854037e-01, 1.8233288878e-01, 1.8537258787e-02, 4.0878848609e-03,
    3.6223027434e+00, 2.1018478835e+00, 7.1241084287e-01, 1.3473722473e-01,
    1.3698343797e-02, 3.0207935660e-03, 1.7286568711e+00, 1.0030563946e+00,
    3.3998094175e-01, 6.4300096385e-02, 6.5372000904e-03, 1.4415977054e-03,
    6.2051124090e-01, 3.6005284091e-01, 1.2203810081e-01, 2.3080876868e-02,
    2.3465585050e-03, 5.1746513213e-04
]).reshape(7, 6)

MAX_TOL = 2.0e-2     # measured cross-method max 1.47e-2 (r=50 pin)
MEDIAN_TOL = 8.0e-3  # measured cross-method median 4.3e-3


@unittest.skipUnless(HAS_DUMP, _SKIP_MSG)
class TestXiNlAgainstFftlog(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        sec = DUMP_DIR / "xi_nl"
        cls.r = np.loadtxt(sec / "r.txt")
        cls.z = np.loadtxt(sec / "z.txt")
        cls.xi = np.loadtxt(sec / "xi_nl.txt").reshape(cls.z.size, cls.r.size)

    def _table_at_pins(self):
        from scipy.interpolate import RegularGridInterpolator
        itp = RegularGridInterpolator((self.z, np.log(self.r)), self.xi)
        pts = np.stack(np.meshgrid(Z_PIN, np.log(R_PIN), indexing="ij"),
                       axis=-1)
        return itp(pts)

    def test_xi_table_matches_independent_fftlog(self):
        dev = np.abs(self._table_at_pins() / XI_FFTLOG_PIN - 1.0)
        self.assertLessEqual(dev.max(), MAX_TOL,
                             f"max cross-method dev {dev.max():.2e}")
        self.assertLessEqual(np.median(dev), MEDIAN_TOL,
                             f"median cross-method dev {np.median(dev):.2e}")

    def test_xi_positive_and_decreasing_over_pins(self):
        vals = self._table_at_pins()
        self.assertTrue(np.all(vals > 0.0))
        self.assertTrue(np.all(np.diff(vals, axis=1) < 0.0))   # falls with r
        self.assertTrue(np.all(np.diff(vals, axis=0) < 0.0))   # falls with z

    def test_z_rows_are_not_degenerate(self):
        # Regression guard on the issue-#4 z-degeneracy failure mode:
        # xi(r=1) must scale like D^2(z), i.e. vary by >2x over z in [0,2].
        i1 = np.argmin(np.abs(self.r - 1.0))
        i_z0 = np.argmin(np.abs(self.z))
        i_z2 = np.argmin(np.abs(self.z - 2.0))
        self.assertGreater(self.xi[i_z0, i1] / self.xi[i_z2, i1], 2.0)


if __name__ == "__main__":
    unittest.main(verbosity=2)
