// Off-Centered Sigma NFW Profile
// Uses an interpolation table (look at data/nfw_off_center/)
// Assumes that datablock has rho_c, concetration
#ifndef Y3_CLUSTER_NFW_DSIGMA_MIS_HH
#define Y3_CLUSTER_NFW_DSIGMA_MIS_HH

#include <algorithm>
#include <iostream>
#include <math.h>
#include <string>

#include "fmt/core.h"

#include <optional>

#include "cosmosis/datablock/datablock.hh"

#include "utils/interp_1d.hh"
#include "utils/interp_2d.hh"
#include "utils/make_interp_2d.hh"
#include "utils/make_interp_1d.hh"
#include "utils/read_vector.hh"

namespace y3_cluster {
  // Default concentration value
  double const CONC = 4.0;

  // Critical density in Msun/Mpc^3
  double const RHOC = 2.77533742639e+11;

  // selects the miscentering kernel ('single','gamma')
  std::string const GAMMA = "gamma";

    // The "single" kernel ships a SIGNED (linear) DeltaSigma table
    // (table_1000_..._deltasigma_signed_single.txt), regenerated by
    // data/nfw_off_center/make_signed_deltasigma_table.py.  The legacy
    // "log_deltasigma" table stored log(DeltaSigma_mis) and was read back as
    // exp(...) -- structurally >= 0 -- which ZEROED the physical negative lobe
    // (DeltaSigma_mis < 0 for r_mis > r, halo center outside the aperture).
    // That broke the mean-field ("rnd") cancellation in the shear projection.
    // The signed table stores DeltaSigma_mis directly (no log), so operator()
    // must NOT exponentiate it; see kernel_is_signed / operator().
    static inline bool
    kernel_is_signed(std::string const& kernel)
    {
      return kernel == "single";
    }

    // Grid axes. The "single" kernel now ships on the CUSP-SAFE (ln xmis,
    // ln q) grid, q = x/xmis: DeltaSigma_mis(x, xmis) has a sign-changing
    // ridge along x = xmis, which on natural (ln x, ln xmis) axes cuts
    // diagonally across grid cells and gets smoothed by bilinear
    // interpolation. On (ln xmis, ln q) that ridge is the vertical line
    // ln q = 0, an EXACT grid node (imported verbatim from CLensPy's
    // src/clenspy/data/nfw_miscentering.npz -- see
    // data/nfw_off_center/import_clenspy_single_table.py for the conversion
    // and review/08272026/issue6_rationale.md for the diagnosis). The "gamma"
    // kernel (population-averaged offset; CLensPy has no equivalent table)
    // stays on the legacy natural (ln x, ln xmis) grid for now -- issue #6's
    // domain-truncation defect there is a separate, not-yet-ported fix.
    static inline std::string
    logxmis_file(std::string const& kernel)
    {
      return kernel_is_signed(kernel)
        ? "nfw_off_center/table_ratio_logxmis.txt"
        : fmt::format("nfw_off_center/table_1000_1e-03_5e+03_{}_logxmis.txt",
                       kernel);
    }

    static inline std::string
    logq_file(std::string const& kernel)
    {
      return "nfw_off_center/table_ratio_logq.txt";
    }

    static inline std::string
    logx_file(std::string const& kernel)
    {
      return fmt::format("nfw_off_center/table_1000_1e-03_5e+03_{}_logx.txt",
                         kernel);
    }

    static inline std::string
    dsigma_table_file(std::string const& kernel)
    {
      return kernel_is_signed(kernel)
        ? fmt::format("nfw_off_center/table_ratio_deltasigma_signed_{}.txt",
                       kernel)
        : fmt::format("nfw_off_center/table_1000_1e-03_5e+03_log_deltasigma_{}.txt",
                       kernel);
    }

    // First interpolation axis: ln q for the (new) signed single kernel,
    // ln x for the (unchanged) legacy gamma kernel.
    static inline std::string
    first_axis_file(std::string const& kernel)
    {
      return kernel_is_signed(kernel) ? logq_file(kernel) : logx_file(kernel);
    }

  // Available miscentering kernels for NFW_DSIGMA_MIS.
  std::string const SINGLE = "single";

  class NFW_DSIGMA_MIS {

    public:
    NFW_DSIGMA_MIS(double c, double rhoc, std::string const& kernel)
      : _c(c),
        _rhoc(rhoc),
        _nfwProfile(read_vector(first_axis_file(kernel)),
                    read_vector(logxmis_file(kernel)),
                    read_vector(dsigma_table_file(kernel))),
        _is_signed(kernel_is_signed(kernel))
    { }

    NFW_DSIGMA_MIS()
    : _c(CONC),
      _rhoc(RHOC),
      _nfwProfile(read_vector(first_axis_file(GAMMA)),
                  read_vector(logxmis_file(GAMMA)),
                  read_vector(dsigma_table_file(GAMMA))),
      _is_signed(kernel_is_signed(GAMMA))

    { }

    // UNIFIED rho_m convention (2026-08-24 decision): use `rho` --
    // haloModel/rho_m_ref = Omega_m rho_crit,0 (1+z_density)^3, identical
    // to the density first_halo_term builds the centred tables with --
    // for BOTH the halo boundary r_200 = [3M/(800 pi rho)]^(1/3) and the
    // amplitude rho_s = delta_c * rho. Production call sites use this
    // instead. Pure normalization factors (legacy Omega_m, the physical
    // (1+z)^2) are applied OUTSIDE by the caller.
    void set_rho_ref(double rho) { _rho_b = rho; }

    // Optional per-mass concentration c(lnM) (issue #13): the lookup
    // tables are universal in x = r/r_s, so ALL concentration
    // dependence is analytic (r_s = r_200/c and delta_c(c)).  When a
    // table is set (e.g. haloModel/{lnM, concentration} = Child18 at
    // one_halo_z), it overrides the fixed _c; clamped outside its
    // lnM range.  Default: unset -> legacy fixed c (= 4).
    void set_concentration_table(Interp1D t) { _c_tab = std::move(t); }
    double conc_at(double lnM) const
    {
      return _c_tab ? _c_tab->clamp(lnM) : _c;
    }

    // Scale radius r_s(M) [cMpc/h], exposed for callers that need it
    // directly (e.g. the frozen-physics r_s(M)-anchored amplitude
    // drift a_b(z)). Additive-only: duplicates the same formula
    // operator() computes inline, so any future change to that formula
    // must be mirrored here.
    double
    r_s(double lnM) const
    {
      double const r_200 = std::cbrt(3.0 * std::exp(lnM) / (800.0 * M_PI * _rho_b));
      return r_200 / conc_at(lnM);
    }

    double
    operator()(double r, double rmis, double lnM) const
    {
      double const c = conc_at(lnM);
      double const delta_c = (200.0 * c * c * c / 3.0) / (std::log(1.0 + c) - c / (1.0 + c));
      double const r_200 = std::cbrt(3.0 * std::exp(lnM) / (800.0 * M_PI * _rho_b));
      double const r_s = r_200 / c;

      double const x = r / r_s;
      double const xmis = rmis / r_s;

      // Dimensionless DeltaSigma_mis(x, xmis) from the lookup table. The
      // signed "single" table is on the cusp-safe (ln xmis, ln q) grid
      // (q = x/xmis; see first_axis_file() above); the legacy "gamma" table
      // stays on the natural (ln x, ln xmis) grid. The "single" table is
      // SIGNED/linear (may be < 0 for xmis > x); the "gamma" table is log,
      // so exponentiate only in that case.
      double const first_axis = _is_signed ? x / xmis : x;
      double const tab = _nfwProfile.clamp(std::log(first_axis), std::log(xmis));
      double const unfw = _is_signed ? tab : std::exp(tab);

      // normalization term defined in Wright & Brainerd 2000
      double const norm = 2 * r_s * delta_c * _rho_b;
      double const nfw = norm * unfw;

      // Conversion from Msun/Mpc^2 to Msun/h pc^2
      return nfw*1e-12;
    }

  private:
    double const _c;
    double const _rhoc;
    double       _rho_b{_rhoc};   // boundary+amplitude density (set_rho_ref)
    std::optional<Interp1D> _c_tab;
    Interp2D _nfwProfile;
    bool const _is_signed;   // true: table stores signed DeltaSigma (no exp)
  };
}
#endif

// USED FOR DEBUGGING
// using printf debugs r200 and r_s
// printf("r200: %f, r_s: %f\n", r_200, r_s);
// printf("delta_c: %f, rho_crit: %f\n", delta_c, rho_crit);
// printf("norm: %f\n", norm);
// printf("conc: %f\n", _c);