"""Miscentred one-halo shear via the radial_series strategy — Python.

The fast shear strategy of src/pipelines/des_y3/README.md
(`radial_series`): no redshift freeze, no per-sample profile
differentiation. Three steps per the approved design:

IMPORTANT LIMITATION: the offline profile is fixed at c = 4 for every mass
and redshift. There is no concentration--mass or concentration--redshift
evolution in U_ell. The exact redshift contraction below applies to the
population weights only; it does not restore a varying production c(M, z)
profile. Use direct radial evaluation rather than this table if that
concentration dependence is required.

  1. offline (once, committed): the unit-profile tables
     U_ell(ln x, ln x_mis), ell = 0..3, generated by
     generate_radial_series_tables.py under data/radial_series/;
  2. per sample: the exact redshift contraction
     W_ij(lnM) = int dz n dV/dOmega/dz Omega S_ij Sigma_crit_inv
     on fixed GL nodes (the SelGLCore convention), then the population
     moments of y = ln r_s(M): N_ij, ybar_ij, mu_2, mu_3;
  3. per (bin, R): interpolate U_0, U_2, U_3 at
     (ln R - ybar, ln r_mis - ybar), restore the analytic amplitude,
     and assemble

     O_ij(R) ~= N_ij A0(ybar) [ u_mix,0 + mu_2 u_mix,2 + mu_3 u_mix,3 ]

     with u_mix,ell = (1 - f_mis) U_ell^cen + f_mis Omega_m U_ell^mis
     (Omega_m is the miscentred component's rho_mult, exactly as
     NFW_DSIGMA_MIS::set_rho_mult).

The observable is the count-weighted stack N_ij[gamma_t^1h,full](R) on
the production (bin_index x r_perp) cartesian grid, bin slow / R fast —
the same grid semantics as Shear1hMisSel. The centred component is the
fixed-convention (c = 4, rho_crit) Wright & Brainerd profile — the
x_mis -> 0 limit of the same family as the miscentred term — NOT the
per-sample haloModel/dSigma_nfw table production uses; the known ~4%
shape difference between those two centred conventions is documented in
README.md and validations (see also validations/README.md and the
radial-factorization study §"two independently-sourced tables").

DataBlock contract
------------------
Reads (ini options):
    bin_index, r_perp             cartesian product grid (bin slow)
    zt_low, zt_high, lnm_low, lnm_high    required GL envelope
    n_lnm, n_z                    GL nodes (defaults 96, 64)
    lob_centers                   default 25 37.5 52.5 130
    ell_max                       2 or 3 (default 2: both the
                                  radial-factorization study and this
                                  implementation's validation find the
                                  mu_3 term does not improve the nearly
                                  symmetric DES Y3 mass weights; 3 is
                                  supported per the approved plan)
    table                         path to the U_ell npz (default
                                  data/radial_series/radial_series_nfw_mis_gamma_v1.npz)
Reads (datablock): the full Shear1hMisSel weight contract —
    sel_function/{lnM,z,S_stack}, mass_function/{m_h,z,dndlnmh},
    cluster_abundance/{hmf_s,hmf_q}, distances/{z,d_a},
    average_sigma_crit_inv/{zlense,sci_average},
    miscentering/{f_mis,tau_mis} (optional; defaults 0.22 / 0.17),
    cosmological_parameters/{h0,omega_m,omega_nu,omega_lambda,omega_k}
Writes:
    shear1h_radial_series/vals    (n_bins * n_r,)
    shear1h_radial_series/{norm,y_eff,mu2,mu3}   per-bin diagnostics

Status: reference/candidate implementation (validated against its own
exact fixed-GL mass integral; see README.md). Not a production entry
point; production remains Shear1hMisSel.so.
"""
from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import numpy as np
from scipy.interpolate import CubicSpline, RectBivariateSpline

for _p in Path(__file__).resolve().parents:
    if (_p / "shared" / "datablock_models.py").is_file():
        if str(_p) not in sys.path:
            sys.path.insert(0, str(_p))
        break

from shared import datablock_models as dm
from systematics.selection_richness.python import sel_kernels

sys.path.insert(0, str(Path(__file__).resolve().parent))
import nfw_profile_family as pf  # noqa: E402

OUTPUT_SECTION = "shear1h_radial_series"
DEFAULT_TABLE = "data/radial_series/radial_series_nfw_mis_gamma_v1.npz"


class RadialSeriesTable:
    """Loader/interpolator for the committed U_ell tables (loaded once)."""

    def __init__(self, path=None):
        if path is None:
            path = pf.repo_root() / DEFAULT_TABLE
        self.path = Path(path)
        with np.load(self.path) as z:
            self.lnx = z["lnx"]
            self.lnxm = z["lnxm"]
            self.meta = json.loads(str(z["meta_json"]))
            self._mis = [RectBivariateSpline(self.lnx, self.lnxm,
                                             z[f"U{ell}_mis"], kx=3, ky=3)
                         for ell in range(4)]
            self._cen = [CubicSpline(self.lnx, z[f"U{ell}_cen"])
                         for ell in range(4)]

    def _clamp(self, lnx, lnxm):
        return (np.clip(lnx, self.lnx[0], self.lnx[-1]),
                np.clip(lnxm, self.lnxm[0], self.lnxm[-1]))

    def u_cen(self, ell, lnx):
        return self._cen[ell](np.clip(lnx, self.lnx[0], self.lnx[-1]))

    def u_mis(self, ell, lnx, lnxm):
        lnx, lnxm = self._clamp(lnx, lnxm)
        return self._mis[ell].ev(lnx, lnxm)

    def u_mix(self, ell, lnx, lnxm, f_mis, rho_mult):
        """(1 - f_mis) U_ell^cen + f_mis rho_mult U_ell^mis."""
        return ((1.0 - f_mis) * self.u_cen(ell, lnx)
                + f_mis * rho_mult * self.u_mis(ell, lnx, lnxm))


def evaluate_series(table, r_perp, r_mis, norm, ybar, mu, *,
                    f_mis, rho_mult, ell_max=3):
    """Assemble O(R) for one bin from the offline tables and moments.

    mu is the central-moment vector from MassZWeights.moments_of (mu[0]=1,
    mu[1]=0); only mu[2] (and mu[3] when ell_max=3) survive.
    """
    lnx = np.log(np.asarray(r_perp, dtype=float)) - ybar
    lnxm = np.full_like(lnx, np.log(r_mis) - ybar)
    acc = table.u_mix(0, lnx, lnxm, f_mis, rho_mult)
    acc = acc + mu[2] * table.u_mix(2, lnx, lnxm, f_mis, rho_mult)
    if ell_max >= 3:
        acc = acc + mu[3] * table.u_mix(3, lnx, lnxm, f_mis, rho_mult)
    return norm * pf.A0_of_y(ybar) * acc


# ---------------------------------------------------------------------------
# CosmoSIS module entry points
# ---------------------------------------------------------------------------

def setup(options):
    from cosmosis.datablock import option_section
    sf = sel_kernels.load()
    cfg = {}
    cfg["bin_index"] = sf._read_array(options, option_section,
                                      "bin_index").astype(int)
    cfg["r_perp"] = sf._read_array(options, option_section, "r_perp")
    try:
        cfg["lob_centers"] = sf._read_array(options, option_section,
                                            "lob_centers")
    except Exception:
        cfg["lob_centers"] = np.asarray(dm.DEFAULT_LOB_CENTERS)
    for key in ("zt_low", "zt_high", "lnm_low", "lnm_high"):
        cfg[key] = float(options.get_double(option_section, key))
    for key, default in (("n_lnm", 96), ("n_z", 64), ("ell_max", 2)):
        try:
            cfg[key] = int(options.get_int(option_section, key))
        except Exception:
            cfg[key] = default
    if cfg["ell_max"] not in (2, 3):
        raise ValueError("shear1h_radial_series: ell_max must be 2 or 3")
    try:
        path = options.get_string(option_section, "table")
    except Exception:
        path = None
    cfg["table"] = RadialSeriesTable(path)   # loaded once, never per sample
    return cfg


def execute(block, cfg):
    t0 = time.perf_counter()
    source = dm.DataBlockSource(block)
    table = cfg["table"]

    weights = dm.MassZWeights(
        source, n_lnm=cfg["n_lnm"], n_z=cfg["n_z"],
        zt_lo=cfg["zt_low"], zt_hi=cfg["zt_high"],
        lnm_lo=cfg["lnm_low"], lnm_hi=cfg["lnm_high"], include_sci=True)
    norm, ybar, mu = weights.moments_of(pf.y_of_lnM, ell_max=3)

    f_mis = dm.read_mis_param(source, "f_mis", dm.F_MIS_DEFAULT)
    tau_mis = dm.read_mis_param(source, "tau_mis", dm.TAU_MIS_DEFAULT)
    omega_m = source.scalar("cosmological_parameters", "omega_m")
    lob = cfg["lob_centers"]

    vals = np.empty(cfg["bin_index"].size * cfg["r_perp"].size)
    n_r = cfg["r_perp"].size
    for i, b in enumerate(cfg["bin_index"]):
        r_mis = tau_mis * float(dm.R_lambda(lob[b % lob.size]))
        vals[i * n_r:(i + 1) * n_r] = evaluate_series(
            table, cfg["r_perp"], r_mis, norm[b], ybar[b], mu[b],
            f_mis=f_mis, rho_mult=omega_m, ell_max=cfg["ell_max"])

    block[OUTPUT_SECTION, "vals"] = vals
    block[OUTPUT_SECTION, "norm"] = norm
    block[OUTPUT_SECTION, "y_eff"] = ybar
    block[OUTPUT_SECTION, "mu2"] = mu[:, 2]
    block[OUTPUT_SECTION, "mu3"] = mu[:, 3]
    dt_ms = 1000.0 * (time.perf_counter() - t0)
    print(f"[shear1h_radial_series] {cfg['bin_index'].size} bins x "
          f"{n_r} radii, ell<={cfg['ell_max']} — {dt_ms:.0f} ms", flush=True)
    return 0


def cleanup(config):
    return 0
